[package]
name = "bow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
compact_str = "0.8.0"
crossterm = "0.28.1"
ratatui = "0.27.0"
thiserror = "1.0.50"
